name: Kitsu Test Suite
on: [push, pull_request]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Node ${{ matrix.node_version}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [22]
        os: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Type Check
        run: pnpm typecheck

      - name: Lint
        run: pnpm eslint .

      - name: Build Client
        run: pnpm build:client

      - name: Build Library
        run: pnpm build:library

      - name: Test App
        run: COVERAGE=true pnpm run test:unit

      - name: Report Test Coverage
        if: github.event_name == 'push' && github.ref == 'refs/heads/react'
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage/lcov.info
          format: lcov
          skip-errors: false
